# Generated by Django 5.2.8 on 2025-12-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=50)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profilepicture/')),
                ('video_resume', models.FileField(blank=True, null=True, upload_to='videoresume/')),
            ],
        ),
    ]
